[package]
name = "dagree_converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fmt = "0.1.0"
inquire = "0.5.3"
tokio = "1.25.0"
